import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSession } from "next-auth/react";
import * as Avatar from "@radix-ui/react-avatar";
import classNames from "clsx";
import { signIn } from "next-auth/react";
import { signOut } from "next-auth/react";
import Router, { useRouter } from "next/router";

const LogOut = () => (
  <button
    onClick={() =>
      signOut({
        callbackUrl: "/login",
      })
    }
  >
    Sign out
  </button>
);

const LogIn = ({}) => (
  <button onClick={() => signIn("credentials")}>Sign in with Email</button>
);

export default function Home() {
  const session = useSession();
  const router = useRouter();

  if(session.status === 'unauthenticated') {
      router.push('/login')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {session.status === "authenticated" && (
          <>
            <LogOut />
            <Avatar.Root
              className={classNames(
                "w-14",
                "h-14",
                "rounded-full",
                "inline-block",
                "overflow-hidden"
              )}
            >
              <Avatar.Image
                className={classNames("w-full", "h-full", "object-cover")}
                src="https://images.unsplash.com/photo-1492633423870-43d1cd2775eb?&w=128&h=128&dpr=2&q=80"
              ></Avatar.Image>
            </Avatar.Root>
          </>
        )}

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <LogIn />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
